name: Release
on:
  push:
    branches: [master]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: npx semantic-release
